api:
  image: quay.io/platformnexus/notification-service:0.1
  environment:
    SPRING_APPLICATION_NAME:
    SPRING_PROFILES_ACTIVE:
    SPRING_CLOUD_CONFIG_URL:
    SPRING_CLOUD_CONFIG_USERNAME:
    SPRING_CLOUD_CONFIG_PASSWORD:
    APP_CONFIG_RECEIVER_ENABLED: 'false'
    HEALTH_CONFIG_ENABLED: 'false'
  labels:
    io.rancher.scheduler.affinity:host_label: notification_service=true
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  volumes:
    - /opt/notification-service/logs:/opt/notification-service/logs
    - /opt/notification-service/conf:/opt/notification-service/conf
  links:
    - redis:redis
    - mysql:mysql
receiver:
  image: quay.io/platformnexus/notification-service:0.1
  environment:
    SPRING_APPLICATION_NAME:
    SPRING_PROFILES_ACTIVE:
    SPRING_CLOUD_CONFIG_URL:
    SPRING_CLOUD_CONFIG_USERNAME:
    SPRING_CLOUD_CONFIG_PASSWORD:
    APP_CONFIG_RECEIVER_ENABLED: 'false'
    HEALTH_CONFIG_ENABLED: 'false'
  labels:
    io.rancher.scheduler.affinity:host_label: notification_service=true
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  volumes:
    - /opt/notification-receiver/logs:/opt/notification-service/logs
    - /opt/notification-receiver/conf:/opt/notification-service/conf
  links:
    - redis:redis
    - mysql:mysql
redis:
  image: redis
  command: redis-server --appendonly yes
  volumes:
    - /data:/data
  labels:
    io.rancher.scheduler.affinity:host_label: infrastructure=true
mysql:
  image: mysql:5.7
  environment:
    - MYSQL_DATABASE=notification
    - MYSQL_USER=platform
    - MYSQL_PASSWORD=Pl@tf0rmNexus
    - MYSQL_ROOT_PASSWORD=Pl@tf0rmNexus
    - TZ=America/Los_Angeles
lb:
  ports:
    - 8000:7000
  labels:
    io.rancher.scheduler.affinity:host_label: lb=true
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  image: rancher/load-balancer-service
  links:
    - api:api
