version: '2'
services:
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      default_cert: platformnexus-wildcard
      port_rules:
      - protocol: http
        service: layer
        source_port: 8000
        target_port: 7000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  mysql:
    scale: 1
    start_on_create: true
  layer:
    scale: 2
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 4000
      port: 7000
      unhealthy_threshold: 3
      interval: 6000
      strategy: recreate
      request_line: GET /health HTTP/1.0
  receiver:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 4000
      port: 7000
      unhealthy_threshold: 3
      interval: 6000
      strategy: recreate
      request_line: GET /health HTTP/1.0
  redis:
    scale: 1
    start_on_create: true
