database:
  image: mysql:5.7
  container_name: mysql_database
  environment:
    - MYSQL_DATABASE=notification
    - MYSQL_USER=felix
    - MYSQL_PASSWORD=felix123
    - MYSQL_ROOT_PASSWORD=felix123
    - TZ=America/Los_Angeles
  ports:
    - "3306:3306"
redis:
  image: "redis"
  command: redis-server --appendonly yes
  ports:
    - "6379:6379"
